name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Run MLflow project
        run: |
          mlflow run MLProject --env-manager=local

      - name: List files before upload
        run: |
          echo "Current directory: $(pwd)"
          ls -R

      - name: Upload MLruns as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-artifact
          path: mlruns

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f 3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest MLflow run ID: $RUN_ID"

      - name: Build Docker image
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "house-price-prediction:latest"

      - name: Log in into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag house-price-prediction ${{ secrets.DOCKER_HUB_USERNAME }}/house-price-prediction:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/house-price-prediction:latest
